baseURL = "https://tender-wiles-5d6778.netlify.app/"
languageCode = "en-us"
title = "Saransh Chauhan"
theme= "PaperMod"
enableemoji= true

[params]
ShowShareButtons= false

[params.homeInfoParams]
Title = "Hi there \U0001F44B" 
Content = '''I'm Saransh. I am a product manager and an entrepreneur in **Austin, TX**. 

I write about product and entrepreneurship; geopolitics; and environmental issues.'''


[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/saransh/"

[[params.socialIcons]]
name = "medium"
url = "https://medium.com/@chauhan.saransh"

[[params.socialIcons]]
name = "github"
url = "https://github.com/schauhan"


[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
identifier = "about"
name = "about me"
url = "/about"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags"
weight = 20

[[menu.main]]
identifier = "search"
name = "search"
url = "/search"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]